export const REQUIRED_TABLES = [
  "users",
  "courses",
  "lectures",
  "enrollments",
  "tests",
  "questions",
  "test_attempts",
  "study_materials",
  "notifications",
  "live_classes",
  "download_tokens",
  "user_downloads",
  "media_tokens",
  "device_block_events",
  "live_class_viewers",
  "live_class_hand_raises",
  "support_messages",
  "admin_notifications",
  "books",
  "book_purchases",
  "book_click_tracking",
  "course_folders",
  "standalone_folders",
  "folder_purchases",
  "test_purchases",
  "site_settings",
  "question_reports",
  "user_sessions",
  "live_class_recording_progress",
  "user_push_tokens",
  "web_push_subscriptions",
  "session",
  "express_rate_limit",
  "otp_challenges",
  "notifications_sent",
  // Tables previously missing from this contract - added for complete coverage.
  "daily_missions",      // 0000 baseline - holds daily drill questions
  "lecture_progress",    // 0000 baseline - per-student lecture watch state
  "payments",            // 0000 baseline - Razorpay payment records
  "user_missions",       // 0035 - per-student daily mission completion records
  // Migration 0017 - live class polling system
  "live_class_polls",
  "live_class_poll_options",
  "live_class_poll_votes",
  "live_class_activity_timers",
  // Migration 0023 - payment failure audit log
  "payment_failures",
  // Migration 0037 - runtime feature flags
  "runtime_feature_flags",
  // Migration 0038 - API idempotency + standalone entitlements + webhook receipts
  "api_idempotency_keys",
  "standalone_material_entitlements",
  "webhook_event_receipts",
  // Migration 0039 - live stream finalize job queue
  "live_stream_finalize_jobs",
  // Migration 0040b - live chat messages (existed in production, was missing from migrations)
  "live_chat_messages",
  // Migration 0043 - per-device server-issued offline encryption secrets (ODSR-01)
  "device_offline_secrets",
  // Migration 0044 - doubts table (was in schema.ts + backend routes but missing from migrations)
  "doubts",
] as const;

export const REQUIRED_COLUMNS: Record<string, string[]> = {
  users: [
    "password_hash",
    "session_token",
    "app_bound_device_id",
    "profile_complete",
    "is_blocked",
    "last_active_at",
    "active_session_platform",
    "otp_send_count",
    "otp_send_window_start",
    "otp_send_locked_until",
  ],
  enrollments: ["status", "valid_until", "download_cleanup_pending"],
  live_classes: [
    "recording_url",
    "stream_type",
    "show_viewer_count",
    "notify_email",
    "notify_bell",
    "chat_mode",
    "cf_stream_uid",
    "cf_playback_hls",
    "lecture_section_title",
    "lecture_subfolder_title",
    "recording_deleted_at",
    "classroom_room_name",
    "board_snapshot_url",
    "board_pdf_url",
    "board_pages_json",
    "board_sync_checkpoint_url",
    "board_checkpoint_at",
    "cf_recording_uid",
    "recording_url_normalized",
  ],
  notifications: ["source", "expires_at", "is_hidden", "admin_notif_id", "image_url"],
  web_push_subscriptions: ["endpoint", "p256dh", "auth", "is_active", "last_seen_at"],
  courses: ["subject", "cover_color", "pyq_count", "mock_count", "practice_count", "teacher_bio", "teacher_image_url", "teacher_details_json", "multi_subject_config", "course_language", "batch_status"],
  lectures: [
    "download_allowed",
    "section_title",
    "live_class_id",
    "live_class_finalized",
    "transcript",
    "video_url_normalized",
    "pdf_url_normalized",
    "subject_key",
  ],
  study_materials: ["download_allowed", "section_title", "file_url_normalized", "subject_key"],
  tests: ["difficulty", "scheduled_at", "price", "mini_course_id", "subject_key"],
  questions: ["image_url", "solution_image_url"],
  lecture_progress: ["playback_sessions", "last_session_ping_at"],
  course_folders: ["parent_id", "subject_key"],
  standalone_folders: ["parent_id", "category", "price", "original_price", "is_free", "description", "validity_months"],
  // Migration 0042 - admin session device binding
  user_sessions: ["device_id"],
};

export const REQUIRED_UNIQUE_INDEX_SPECS = [
  { table: "enrollments", columns: ["user_id", "course_id"] },
  { table: "user_downloads", columns: ["user_id", "item_type", "item_id"] },
  { table: "user_missions", columns: ["user_id", "mission_id"] },
  { table: "payments", columns: ["razorpay_order_id"] },
  { table: "lecture_progress", columns: ["user_id", "lecture_id"] },
  { table: "live_class_viewers", columns: ["live_class_id", "user_id"] },
  { table: "live_class_hand_raises", columns: ["live_class_id", "user_id"] },
  { table: "book_purchases", columns: ["user_id", "book_id"] },
  { table: "folder_purchases", columns: ["user_id", "folder_id"] },
  { table: "test_purchases", columns: ["user_id", "test_id"] },
  { table: "question_reports", columns: ["question_id", "user_id"] },
  { table: "book_click_tracking", columns: ["user_id", "book_id"] },
  { table: "site_settings", columns: ["key"] },
  { table: "user_push_tokens", columns: ["expo_push_token"] },
  { table: "web_push_subscriptions", columns: ["endpoint"] },
  { table: "users", columns: ["phone"] },
  { table: "users", columns: ["email"] },
  { table: "notifications_sent", columns: ["class_id", "user_id", "type"] },
  // Migration 0038
  { table: "api_idempotency_keys", columns: ["user_id", "scope", "idempotency_key"] },
  { table: "standalone_material_entitlements", columns: ["user_id", "material_id"] },
  { table: "webhook_event_receipts", columns: ["source", "event_id"] },
  // Migration 0039
  { table: "live_stream_finalize_jobs", columns: ["live_class_id"] },
  // Migration 0043 - per-device offline encryption secrets
  { table: "device_offline_secrets", columns: ["user_id", "device_id"] },
] as const;
