export const REQUIRED_TABLES = [
  "users",
  "courses",
  "lectures",
  "enrollments",
  "tests",
  "questions",
  "test_attempts",
  "study_materials",
  "notifications",
  "live_classes",
  "download_tokens",
  "user_downloads",
  "media_tokens",
  "device_block_events",
  "live_class_viewers",
  "live_class_hand_raises",
  "support_messages",
  "admin_notifications",
  "books",
  "book_purchases",
  "book_click_tracking",
  "course_folders",
  "standalone_folders",
  "folder_purchases",
  "test_purchases",
  "site_settings",
  "question_reports",
  "user_sessions",
  "live_class_recording_progress",
  "user_push_tokens",
  "session",
  "express_rate_limit",
  "otp_challenges",
] as const;

export const REQUIRED_COLUMNS: Record<string, string[]> = {
  users: [
    "session_token",
    "app_bound_device_id",
    "web_device_id_phone",
    "web_device_id_desktop",
    "profile_complete",
    "is_blocked",
    "last_active_at",
    "otp_send_count",
    "otp_send_window_start",
    "otp_send_locked_until",
  ],
  enrollments: ["status", "valid_until"],
  live_classes: [
    "recording_url",
    "stream_type",
    "show_viewer_count",
    "notify_email",
    "notify_bell",
    "chat_mode",
    "cf_stream_uid",
    "cf_playback_hls",
    "lecture_section_title",
    "lecture_subfolder_title",
    "recording_deleted_at",
  ],
  notifications: ["source", "expires_at", "is_hidden", "admin_notif_id", "image_url"],
  courses: ["subject", "cover_color", "pyq_count", "mock_count", "practice_count"],
  lectures: ["download_allowed", "section_title", "live_class_id", "live_class_finalized"],
  study_materials: ["download_allowed", "section_title"],
  tests: ["difficulty", "scheduled_at", "price", "mini_course_id"],
  questions: ["image_url", "solution_image_url"],
  lecture_progress: ["playback_sessions", "last_session_ping_at"],
  standalone_folders: ["category", "price", "original_price", "is_free", "description", "validity_months"],
};

export const REQUIRED_UNIQUE_INDEX_SPECS = [
  { table: "enrollments", columns: ["user_id", "course_id"] },
  { table: "user_downloads", columns: ["user_id", "item_type", "item_id"] },
  { table: "user_missions", columns: ["user_id", "mission_id"] },
  { table: "payments", columns: ["razorpay_order_id"] },
  { table: "lecture_progress", columns: ["user_id", "lecture_id"] },
  { table: "live_class_viewers", columns: ["live_class_id", "user_id"] },
  { table: "live_class_hand_raises", columns: ["live_class_id", "user_id"] },
  { table: "book_purchases", columns: ["user_id", "book_id"] },
  { table: "folder_purchases", columns: ["user_id", "folder_id"] },
  { table: "test_purchases", columns: ["user_id", "test_id"] },
  { table: "question_reports", columns: ["question_id", "user_id"] },
  { table: "book_click_tracking", columns: ["user_id", "book_id"] },
  { table: "site_settings", columns: ["key"] },
  { table: "user_push_tokens", columns: ["expo_push_token"] },
  { table: "users", columns: ["phone"] },
  { table: "users", columns: ["email"] },
] as const;
