export const REQUIRED_TABLES = [
  "users",
  "courses",
  "lectures",
  "enrollments",
  "tests",
  "questions",
  "test_attempts",
  "study_materials",
  "notifications",
  "live_classes",
  "download_tokens",
  "user_downloads",
  "media_tokens",
  "device_block_events",
  "live_class_viewers",
  "live_class_hand_raises",
  "support_messages",
  "admin_notifications",
  "books",
  "book_purchases",
  "book_click_tracking",
  "course_folders",
  "standalone_folders",
  "folder_purchases",
  "test_purchases",
  "site_settings",
  "question_reports",
  "user_sessions",
] as const;

export const REQUIRED_COLUMNS: Record<string, string[]> = {
  users: ["session_token", "app_bound_device_id", "profile_complete", "is_blocked", "last_active_at"],
  enrollments: ["status", "valid_until"],
  live_classes: [
    "recording_url",
    "stream_type",
    "show_viewer_count",
    "notify_email",
    "notify_bell",
    "chat_mode",
    "cf_stream_uid",
    "cf_playback_hls",
    "lecture_section_title",
    "lecture_subfolder_title",
  ],
  notifications: ["source", "expires_at", "is_hidden", "admin_notif_id", "image_url"],
  courses: ["subject", "cover_color", "pyq_count", "mock_count", "practice_count"],
  lectures: ["download_allowed", "section_title"],
  study_materials: ["download_allowed", "section_title"],
  tests: ["difficulty", "scheduled_at", "price", "mini_course_id"],
  questions: ["image_url", "solution_image_url"],
  standalone_folders: ["category", "price", "original_price", "is_free", "description", "validity_months"],
};
